# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('inrpp', ['core','internet', 'network'])
    module.source = [
        'model/inrpp-route.cc',        
        'model/inrpp-cache.cc',
        'model/inrpp-l3-protocol.cc',    
        'model/inrpp-header.cc',  
        'model/inrpp-interface.cc',                  
        'helper/inrpp-stack-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('inrpp')
#    module_test.source = [
#        'test/mac-extension-test-suite.cc',
#        'test/ocb-test-suite.cc',
#        ]

    headers = bld(features='ns3header')
    headers.module = 'inrpp'
    headers.source = [
        'model/inrpp-route.h',        
        'model/inrpp-cache.h',        
        'model/inrpp-l3-protocol.h',    
        'model/inrpp-header.h',
        'model/inrpp-interface.h',                          
        'helper/inrpp-stack-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    bld.ns3_python_bindings()

